### PR TITLE
add documentation MINTGenerator

### PR DESCRIPTION
**Pull request by JorgeLuizFranco**
Add documentation for the MINTGenerator

### CODE REVIEW

**Comment by pat-alt** [comment]
@JorgeLuizFranco the file should now render without issues if you're using the latest version of Quarto

**Comment by pasq-cat** [comment]
i have been reading some of the papers you cited. lot of interesting stuff!

**Review by pat-alt — APPROVED** [review]

**Review by pat-alt — CHANGES_REQUESTED** [review]
@JorgeLuizFranco nice work! Only thing that still needs to be done is to rerender the .qmd one more time (usage section is missing from .md) and then adding this section in the docs/make.jl file

**Comment by pasq-cat** [comment]
is there any resource other than the karimi pdf to understand this generator?  something easier... i do not grasp this pdf completely

**Comment by JorgeLuizFranco** [comment]
> is there any resource other than the karimi pdf to understand this generator? something easier... i do not grasp this pdf completely

@pasq-cat , maybe this video could help: https://www.youtube.com/watch?v=3ngjeesGePU&t=779s

**Comment by pasq-cat** [comment]
@JorgeLuizFranco  thanks but i have understood the theory, what is not clear to me is how are the actions counted in practice

**Pull request merged**
