### PR TITLE
Penalty strength notebook and UMAP report

### PR DESCRIPTION
**Pull request by VincentPikand**

### CODE REVIEW

**Review by RaunoArike — APPROVED** [review]
Not much to comment on - LGTM!

**Review by RaunoArike — CHANGES_REQUESTED** [review]
Actually, forgot about one detail in my previous review: please add the paths of the files you added here to our `README.md`.

**Review by RaunoArike — APPROVED** [review]
My previous suggestion will be applied by Mariusz under another branch, so I'll reapprove.

**Review by laurikskl — APPROVED** [review]
LGTM, sad we couldn't make it work, would have been quite cool to get that kind of representation.

**Pull request merged**
