### PR TITLE
Add faithfulness metric

### PR DESCRIPTION
**Pull request by pat-alt**
## Observations

- Posterior sampling is very sensitive to scale of underlying data (step size for SGLD is in absolute terms).

## To Do

- [x] ~Need to ensure that is standardized/normalized before running sampling.~ Can instead just make the parameters for the sampling rule (ImproperSGLD) dependent on the second moment of the prior distribution.
- [x] Get rid of clipping again.
- [x] Support for mini-batch sampling?
- [x] Make `EnergySampler` part of model `M.fitresult` so that it can be recycled.
- [x] ~Add MLJFlux extension~ #469 
- [x] Actually train a good model in JEM.jl
- [ ] Complete tutorial
- [x] Closer look at role of reg loss
- [x] Let decay depend on maximum number of iterations
- [x] ~Why not use Normalized Compression Distance?~ Only available package only applicable to strings
- [x] Cosine distance has advantage of being (-1,1)
- [x] Add `EnergySamplers` dependency

## Notes

Cosine distance works kind of well, but the problem is that scale independence leads to issues such as this one

```julia
julia> dist([1,2],[1,0])
0.5527864045000421

julia> dist([100,200],[1,0])
0.5527864045000421
```

where the cosine distance is the same in both cases even though the counterfactual is way off domain.

### CODE REVIEW

**Comment by pat-alt** [comment]
@alifarukyucel to see

**Comment by mschauer** [comment]
Is faithful here different or equal to from graphical "faithfulness"?  https://www.cmu.edu/dietrich/philosophy/docs/scheines/introtocausalinference.pdf

**Comment by pat-alt** [comment]
Hi @MaritRadder, tagging you here already but the tutorial is still bare bones (just code). I'll try to fill it with some text asap and will probably merge this then and complete the remaining tasks here in another PR.

**Comment by pat-alt** [comment]
@MaritRadder the code here is already updated: `TaijaBase.Samplers` has been moved into its own new package [EnergyBasedSamplers](https://github.com/JuliaTrustworthyAI/EnergySamplers.jl).

**Pull request merged**
