### PR TITLE
Reallocate interoperability functionality

### LINKED ISSUE #329: Reallocation of `extensions` folder
Reallocating the `extensions` folders from the `CounterfactualExplanations.jl` package to the newly created `TAIJA interoperability` package.

- [x] Create TaijaInteroperability sub-package
- [x] Move the `extensions` folder to the newly created package (both source-code and tests)
- [x] Remove the `extensions` folder from this package
- [x] Update the `src/deprecated.jl` file
- [x] Update the documentation

Related to #326.

### PR DESCRIPTION
**Pull request by kmariuszk**
Reallocating interoperability functionality to `TaijaInteroperability.jl` package.

Closes #329.

### CODE REVIEW

**Comment by kmariuszk** [comment]
Pipeline for Julia 1.8 and nightly is failing due to unrelated reasons (it also fails on the main branch) but @pat-alt do you know what might be causing the `CI / Documentation (pull request)` pipeline's fail?

**Comment by pat-alt** [comment]
> Pipeline for Julia 1.8 and nightly is failing due to unrelated reasons (it also fails on the main branch) but @pat-alt do you know what might be causing the `CI / Documentation (pull request)` pipeline's fail?

This is weird, it doesn't give me any information other than 'job failed'

**Comment by pat-alt** [comment]
I've just triggered a rerun now @kmariuszk, because tests for docs are passing in other places (e.g. https://github.com/JuliaTrustworthyAI/CounterfactualExplanations.jl/pull/357)

**Comment by kmariuszk** [comment]
Hey @pat-alt, I updated the documentation accordingly and wanted to double-check if everything works by re-rendering it (even though the "Documentation" pipeline is passing). Could you please help me with it? It could be either locally or in the repo.

**Review by pat-alt — APPROVED** [review]
I love this: +16 −650 

Happy to merge, just restating my stupid questions from teams here: do you guys know if you can safely merge PR that have unmerged commits from main? Otherwise we'd have to now update each of the PRs after we've merged another PR

**Comment by kmariuszk** [comment]
> Happy to merge, just restating my stupid questions from teams here: do you guys know if you can safely merge PR that have unmerged commits from main? Otherwise we'd have to now update each of the PRs after we've merged another PR

If I understand you correctly, it's completely fine to do so if there's no conflicting files. If there are, git is going to complain about this and find the merge conflicts. So, in that sense, it's always safe to merge such PR.

**Pull request merged**
