### PR TITLE
Package extensions for EvoTrees and LaplaceRedux

### LINKED ISSUE #301: Pkg Extensions: EvoTrees, MLJDecisionTreeInterface, NearestNeighborModels, LaplaceRedux

### PR DESCRIPTION
**Pull request by RaunoArike**
Closes #301. Accordingly with that issue:

- Created package extensions for EvoTrees and LaplaceRedux models.
- Removed the NearestNeighborModels dependency: it wasn't used as a dependency for any actual functionality in the package, so I assume it's a leftover from some past functionality that isn't used anymore and can safely be removed from the package.
- Since the MLJDecisionTreeInterface.jl and DecisionTree.jl packages are pretty light and form a core part of the Feature Tweak algorithm, which we don't want to move out of the main package, these remain dependencies of the core package.

### CODE REVIEW

**Review by pat-alt — COMMENTED** [review]
Great! Just one question: do we do usual tests (model predictions and also counterfactual generation) for these somewhere?

**Comment by RaunoArike** [comment]
> Great! Just one question: do we do usual tests (model predictions and also counterfactual generation) for these somewhere?

I checked this now and turns out that the tests for all generators aside from the Feature Tweak tests (which are run for DecisionTrees and RandomForests) use `Models.standard_models_catalogue`, which only contains LinearModel, FluxModel, and FluxEnsemble. Model predictions are tested for EvoTrees, but not for LaplaceRedux. From the time of the software project, I faintly remember us discussing that the LaplaceRedux models are missing something from being fully differentiable and that they weren't ready for counterfactual generation yet because of that, which is also why methods like `train()` haven't been implemented for it, though please correct me if I'm wrong. As for EvoTrees, I think we got it working with Growing Spheres during the software project, but it doesn't seem like counterfactual generation tests are being run for it at the moment.

**Comment by pat-alt** [comment]
> As for EvoTrees, I think we got it working with Growing Spheres during the software project, but it doesn't seem like counterfactual generation tests are being run for it at the moment.

ok, thanks for checking. Would it be straightforward enough to add that here?

**Comment by RaunoArike** [comment]
> > As for EvoTrees, I think we got it working with Growing Spheres during the software project, but it doesn't seem like counterfactual generation tests are being run for it at the moment.
> 
> ok, thanks for checking. Would it be straightforward enough to add that here?

Sorry, forgot about this PR for a while. I added this test, but an error came up somewhere inside the `growing_spheres_generation()` method. I haven't worked on Growing Spheres, so I think it's better if I resolve this together with Mariusz - I'll create an issue for this. In the meantime, I think it's fine to merge this PR, since the initialization of EvoTrees as an extension worked well and the error is coming from the counterfactual generation process which is unrelated to this PR, but @pat-alt let me know if you have a different opinion on this.

**Comment by pat-alt** [comment]
> > > As for EvoTrees, I think we got it working with Growing Spheres during the software project, but it doesn't seem like counterfactual generation tests are being run for it at the moment.
> > 
> > 
> > ok, thanks for checking. Would it be straightforward enough to add that here?
> 
> Sorry, forgot about this PR for a while. I added this test, but an error came up somewhere inside the `growing_spheres_generation()` method. I haven't worked on Growing Spheres, so I think it's better if I resolve this together with Mariusz - I'll create an issue for this. In the meantime, I think it's fine to merge this PR, since the initialization of EvoTrees as an extension worked well and the error is coming from the counterfactual generation process which is unrelated to this PR, but @pat-alt let me know if you have a different opinion on this.

Happy new year 🥳  agree this should be merged

**Comment by RaunoArike** [comment]
Happy new year! After fixing the conflicts, I'm now getting the error `DataDeps.NoValidPathError("No writable path exists to save the data.")` for a few tests on Julia 1 and Julia 1.10. I'm a bit confused about this, I don't think my PR is influencing anything about how `DataDeps` works. @pat-alt any idea why I'm getting this?

**Comment by pat-alt** [comment]
> Happy new year! After fixing the conflicts, I'm now getting the error `DataDeps.NoValidPathError("No writable path exists to save the data.")` for a few tests on Julia 1 and Julia 1.10. I'm a bit confused about this, I don't think my PR is influencing anything about how `DataDeps` works. @pat-alt any idea why I'm getting this?

I was going to say that it may have to do with artifacts and serialization, but it seems to be passing now, so I think this can be merged (not sure why coverage has gone down a bit here)

**Comment by RaunoArike** [comment]
> I was going to say that it may have to do with artifacts and serialization, but it seems to be passing now, so I think this can be merged (not sure why coverage has gone down a bit here)

Seems like it was just a faulty run then, the change that I committed after my last comment was completely trivial. I think the reason coverage went down is just that I uncommented the final two lines of `laplace_redux.jl` when moving the code to the extension folder. I think those lines should remain uncommented, so once you approve, this is ready for merge.

**Review by pat-alt — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
