### PR TITLE
328 reallocate data folder

### LINKED ISSUE #328: Reallocation of `data` folder
Reallocating the `data` folders from the `CounterfactualExplanations.jl` package to the newly created `TAIJA data` package.

- [x] Create TaijaData sub-package
- [x] Move the `data` folder to the newly created package (both source-code and tests)
- [x] Remove the `data` folder from this package
- [x] Update the `src/deprecated.jl` file
- [ ] Update the documentation

### PR DESCRIPTION
**Pull request by kmariuszk**
Closes #328.

### CODE REVIEW

**Comment by pat-alt** [comment]
Happy for this and #329 to be merged once

- [ ] tests are passing
- [ ] functions are deprecated
- [ ] docs are updated (would just add `using TaijaData` to `setup_docs.jl`)

**Comment by pat-alt** [comment]
@kmariuszk does this still need to be open or will it be outdated since #359?

**Comment by kmariuszk** [comment]
> @kmariuszk does this still need to be open or will it be outdated since #359?

Yeah, I'm going to delete all of the reallocated code in this PR, so it should still be opened. Although, I may need to open another PR for this due to the high number of conflicts

**Review by pat-alt — APPROVED** [review]
Perfect, thanks!

**Pull request merged**
